### ISSUE TITLE
something off with kit-status-select

### ISSUE THREAD

**Issue by eko234** [chambln/kakoune-kit#1]
Hi fren, I'm trying out your plugin, thanks in advance for your cool implementation/idea, I was navigating my git log and found that kit-log-select jumps to the wrong capture with certain words, my commit message was `added x feature` and the selection got on added instead of the commit id, so after removing a white space in the regex it works well for me, I don't know if it is important for some reason but I'd like to ask you to check it out:

before:
`<a-x>2s^[\*|\\ /_]*(\w+ )?(\b[0-9a-f]{4,40}\b)<ret><a-:>`
after:
`<a-x>2s^[\*|\\ /_]*(\w+)?(\b[0-9a-f]{4,40}\b)<ret><a-:>`

thanks again!

**Comment by chambln** [comment]
Well spotted! I'll patch it as per your suggestion. Cheers.

**Comment by eko234** [comment]
thanks again @chambln   :D
